### ISSUE TITLE
로그인 페이지를 홈화면에서 바로 로그인 할 수 있도록 모달 방식으로 리디자인한다.

### ISSUE THREAD

**Issue by jeongwusi** [woowacourse-teams/2023-yozm-cafe#144]
## 📑 작업 사항

로그인 페이지를 홈화면에서 바로 로그인 할 수 있도록 모달 방식으로 리디자인한다.

## To-do
- [ ] 모달 컴포넌트 생성
- [ ] 로그인 버튼 컴포넌트 수정
- [ ] 카카오 svg 크기 줄이기
