### ISSUE TITLE
CI / CD 구축

### ISSUE THREAD

**Issue by donghae-kim** [woowacourse-teams/2023-yozm-cafe#2]
## 📑 작업 사항

> CI/CD 파이프라인 구축

## To-do
- [x] CI / CD 툴 선정
- [x] 파이프라인 설계 및 구축
- [x] 프론트엔드 CI / CD 구축 (#12)

## 🎸 기타사항

> 없음
