### ISSUE TITLE
프론트엔드 초기 작업

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#20]
## 📑 작업 사항

프론트엔드 초기 셋업을 진행한다.

## To-do
- [x] react-router 설정
- [x] MSW 설정
- [x] 디자인 시스템 셋업
- [x] 기본 화면 구성 (CSS, 페이지)
