### ISSUE TITLE
홈화면에서 모달, 공유, 좋아요 아이콘의 크기와 모양을 수정한다.

### ISSUE THREAD

**Issue by jeongwusi** [woowacourse-teams/2023-yozm-cafe#200]
## 📑 작업 사항

홈화면에서 모달, 공유, 좋아요 아이콘의 크기와 모양을 수정한다.

## To-do
- [ ] 모달 아이콘 수정
- [ ] 좋아요 아이콘 크기 수정
- [ ] 공유 아이콘 크기 수정

## 🎸 기타사항
