### ISSUE TITLE
프론트엔드 PR 테스트 GitHub Actions 스크립트 작성

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#27]
## 📑 작업 사항
* PR의 프론트엔드 코드에 문제가 발생한 경우 Merge를 막기 위함

## To-do
- [x] GitHub Actions 스크립트 작성
- [x] 웹팩 빌드로 테스트
- [x] 타입스크립트 타입 테스트

## 🎸 기타사항
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/085bb8bb-7d5f-4459-a808-e749da70ba77)

**Comment by jeongwusi** [comment]
기타 사진 낭만있네 ㅋㅋㅋㅋㅋ
