### ISSUE TITLE
스와이프를 통해 좌우의 사진을 볼 수 있도록 한다.

### ISSUE THREAD

**Issue by jeongwusi** [woowacourse-teams/2023-yozm-cafe#287]
## 📑 작업 사항

- 스와이프를 통해 좌우의 사진을 볼 수 있도록 한다.

## To-do
- [ ] 좌우로 스와이프 할 수 있는 기능 추가
- [ ] 전체 사진과 현재 사진이 몇 번째인지 알려주는 Dot UI 추가
- [ ] 전체 사진과 현재 사진이 몇 번째인지 알려주는 숫자 UI 추가

## 🎸 기타사항

> 기타 사항을 작성해주세요
