### ISSUE TITLE
카페 상세정보 보기 바텀시트 UI 개선

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#299]
## 📑 작업 사항
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/2c210d0a-8e19-427c-90a4-865f10fe0f22)

카페 상세정보 보기 바텀시트 UI를 개선한다. 작업 내용은 To-do를 참고한다.

## To-do
- [ ] 지도 링크 아이콘 변경
- [ ] 외부 링크 추가(네이버 지도, 카카오맵, 인스타그램)
- [ ] 리뷰를 바로 볼 수 있는 외부 링크 추가

## 🎸 기타사항
