### ISSUE TITLE
운영 환경을 코드화하여 관리한다

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#424]
## 📑 작업 사항
운영(prod) 서버에서 사용되는 여러 서비스들(Nginx, certbot, MySQL)을 코드화하여 관리한다.

> 운영 서버(혹은 개발 서버)의 코드가 관리되지 않고 있습니다. 서버에서 사용하는 docker-compose.yml 파일이 client에 있는데 이는 SCM으로 관리되지도 않고 client 폴더에 있는 docker-compose.yml 파일이 정말로 사용되는 파일인지도 예상하기도 어렵습니다. (왜냐면 client/docker-compose.yml 파일은 보통 프론트엔드 개발 환경에서 주로 사용하기 때문입니다 ...)
>
> 따라서 infrastructure 폴더 안에 docker-compose.yml 을 만들고 따로 관리하도록 합니다.

코드화 대상
* nginx
* certbot
* MySQL

## To-do
- [x] 운영 환경 docker-compose.yml 작성
- [x] certbot 추가 및 테스트
- [x] nginx 설정 파일 추가
- [x] infrastructure 운영 방법 문서 추가

## 🎸 기타사항
