### ISSUE TITLE
로딩 성능 최적화

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#439]
## 📑 작업 사항
* 웹 사이트의 로딩 성능을 최적화합니다.
* 회의에서 이야기한대로 성능 목표치를 달성하기 위해 최적화를 진행합니다.

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/b1b93da9-fbd5-408e-b983-f702d88331dd)

* lighthouse 결과

![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/86489f4e-79cb-4e9d-9d9b-8958aa86348f)

* [webpagetest 결과](https://www.webpagetest.org/result/230906_AiDc4X_465/)

## To-do
- [ ] Lighthouse 측정 결과를 지속적으로 볼 수 있도록 lighthouse-ci 셋업
- [ ] 성능 예산을 설정하는 lighthouse budget 파일 추가
- [ ] 목표 성능 달성

## 🎸 기타사항
* lighthouse-ci 문서: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md
