### ISSUE TITLE
지도 기능

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-yozm-cafe#451]
## 📑 작업 사항

>  클라이언트에서 지정한 위치로부터 반경 300m 안에 있는 카페의 간략한 정보를 보여준다.

## To-do
- [x] Cafe Table 좌표 Column(Coordinate) 추가
- [x] 좌표 Column에 INDEX 설정
- [x] 기존 데이터에 좌표 데이터 추가 삽입
- [x] 좌표를 추가할 수 있는 api 추가

## 🎸 기타사항

> 기타 사항을 작성해주세요
