### ISSUE TITLE
비회원 카페 정보 조회 API

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-yozm-cafe#47]
## 📑 작업 사항

> 카페 이미지 카드를 조회한다.

## To-do
- [x] 비회원인 경우 DB에 저장된 카페정보들을 순서대로 보여준다.
  - [x] 카페정보는 한번에 5개씩 전달한다.
  - [x] 요청받은 페이지에 해당하는 데이터가 없는 경우 빈배열을 응답한다. 
 
## 🎸 기타사항

> - 좋아요 여부 추후 추가,
> - 좋아요 갯수 추후 추가
