### ISSUE TITLE
홈 화면의 오른쪽 버튼들(`CafeActionBar`) 디자인 개선

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#53]
## 📑 작업 사항
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/79095d85-8e83-46b4-99dd-97ae67574f96)

오른쪽 버튼들의 디자인을 개선한다.

## To-do
- [x] 아이콘의 크기를 통일한다.
- [x] 댓글 아이콘을 outlined -> contained로 수정한다.
- [x] box shadow 를 추가한다.
- [x] 댓글 버튼, 공유하기 버튼 아래에 텍스트를 표시한다.
