### ISSUE TITLE
로그인 API 모킹 및 기능 구현

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#54]
## 📑 작업 사항
로그인 API 모킹과 기능을 구현한다.

## To-do
- [ ] MSW로 로그인 API를 모킹한다.
- [ ] 로그인 여부 상태를 관리한다.
- [ ] 네비게이션 바에 프로필 아이콘이 사용자 이미지로 표시되어야 한다.

## 🎸 기타사항
