### ISSUE TITLE
테스트 성능 개선 및 인수테스트 리팩토링

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-yozm-cafe#544]
## 📑 작업 사항

테스트 속도개선 및 인수테스트 리팩토링
인수테스트가 검증방법도 제각각이고, `RestDocs` 때문에 중요한 로직이 좀 묻히는 느낌이 들더라구요.
그래서 이부분들 리팩토링 하면 좋을것 같아요 ㅎ

## To-do
- [x] `Application Context` 생성 최소화
- [x] yml 에 `log` 옵션을 추가해서 전체적으로 로그를 키고 끌수 있게끔 변경
- [x] 인수테스트 검증방식 통일
- [x] 인수테스트에서 문서화를 위한 코드 분리
 

## 🎸 기타사항

> 기타 사항을 작성해주세요
