### ISSUE TITLE
인프라 개편 (백엔드 dockerize 및 현재 운영 구조 코드에 반영)

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#611]
## 📑 작업 사항
현재 운영되고 있는 인프라 구조를 코드에 반영
* 두 개의 환경(dev, prod)에서 dev 삭제, prod만 운영됨에 따라 이를 코드에 반영
* 운영 편의를 위해 백엔드 Spring Application dockerize하여 운영
  - `nohup` 혹은 `screen` 등의 백그라운드 실행 명령으로 운영할 시 명령어를 외우기가 어려움 (`java -jar -Dspring.profile 어쩌구저쩌구`)
  - 인스턴스 재부팅 시 직접 다시 명령을 입력해주어야 하는 불편함 有

## To-do
- [x] infrastructure/prod 폴더 내 파일들을 infrastructure 로 이동
- [x] Spring App docker 컨테이너 docker-compose.yml에 추가
- [x] nginx https 설정 및 certbot 삭제
  - https는 cloudfront에서 기능하기 때문에 nginx 측에서 설정하지 않아도 됨

## 🎸 기타사항
