### ISSUE TITLE
사용자의 cafe 조회 기록을 반영하는 api 개발

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-yozm-cafe#71]
## 📑 작업 사항

> - [ ] 사용자가 조회한 카페를 해당 사용자의 기록에서 삭제한다.

## To-do
- [ ] 사용자가 조회한 카페를 UnViewedCafe 테이블에서 삭제한다.
- [ ] 사용자의 UnViewedCafe가 모두 삭제 되었을 시, 다시 카페 정보를 갱신한다.
    - [ ] 카페정보를 unViewedCafe에 넣을 시에 순서를 랜덤하게 정렬하여 저장한다.
