### ISSUE TITLE
버튼의 크기, 색상 수정 그리고 시연을 위한 로직 수정

### ISSUE THREAD

**Issue by jeongwusi** [woowacourse-teams/2023-yozm-cafe#79]
## 📑 작업 사항

버튼의 크기, 색상 수정 그리고 시연을 위한 로직 수정

## To-do
- [x] 좋아요 버튼 색상 수정
- [x] 공유하기 버튼의 모양과 크기 조절
- [x] 댓글 버튼의 모양과 크기 조절
- [x] 로그인 버튼의 a 태그 url 수정
- [x] 시연을 위한 좋아요 카운트 로직 수정

## 🎸 기타사항

> 기타 사항을 작성해주세요
